# Generated by Django 2.2.4 on 2019-08-10 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('img', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
