# Generated by Django 2.2.4 on 2019-08-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_coursel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coursel',
        ),
    ]
