# Generated by Django 2.2.4 on 2020-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='sobre_fundadora',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicos',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
