# Generated by Django 2.2.4 on 2020-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_auto_20200813_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='nome',
        ),
        migrations.AddField(
            model_name='eventos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='title',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
