# Generated by Django 2.2.4 on 2020-08-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_auto_20200813_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracao',
            old_name='valor',
            new_name='valores',
        ),
        migrations.AddField(
            model_name='depoimentos',
            name='funcao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depoimentos',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
