# Generated by Django 2.2.4 on 2020-08-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_auto_20200822_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='valores',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='localizacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
