# Generated by Django 2.2.4 on 2020-08-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_auto_20200823_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
