# Generated by Django 2.2.4 on 2020-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_configuracao_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='message_whatsapp',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
