# Generated by Django 2.2.4 on 2020-08-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0008_configuracao_message_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='imagem_fundadora',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
