# Generated by Django 2.2.4 on 2020-08-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0009_configuracao_imagem_fundadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
