# Generated by Django 2.2.4 on 2020-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0010_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='frase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
