# Generated by Django 2.2.4 on 2020-08-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0011_configuracao_frase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='ddd',
            field=models.CharField(default=54, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='message_whatsapp',
            field=models.CharField(help_text='Mensagem para iniciar conversa pelo whatsapp', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='sobre',
            field=models.TextField(help_text='Sobre a Empresa'),
        ),
    ]
