# Generated by Django 2.2.4 on 2020-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0012_auto_20200824_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='list_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ListServicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('servico', models.ForeignKey(on_delete='SET NULL', to='administracao.Servicos')),
            ],
        ),
    ]
