# Generated by Django 2.2.4 on 2020-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0013_auto_20200828_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ministrantes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='imagem_fundadora',
            field=models.ImageField(upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='logo',
            field=models.ImageField(upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_ini',
            field=models.DateField(verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='horario_ini',
            field=models.TimeField(verbose_name='Horário de Inicio'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Titulo'),
        ),
    ]
