# Generated by Django 2.2.4 on 2020-08-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0014_auto_20200828_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração do Site', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='depoimentos',
            options={'verbose_name': 'Depoimento', 'verbose_name_plural': 'Depoimentos'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='listservicos',
            options={'verbose_name': 'Lista de itens', 'verbose_name_plural': 'Listas de itens'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ministrantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listservicos',
            name='servico',
            field=models.ForeignKey(on_delete='SET NULL', related_name='list_service', to='administracao.Servicos'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='icon',
            field=models.CharField(default='ion-ios-paper-outline', max_length=50, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='list_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo para check list'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='metodologia',
            field=models.TextField(verbose_name='Metodologia'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
