# Generated by Django 2.2.4 on 2020-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0016_auto_20201014_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Lista de itens',
                'verbose_name_plural': 'Listas de itens',
            },
        ),
    ]
