# Generated by Django 2.2.4 on 2020-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0017_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimentos',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='link',
        ),
        migrations.AddField(
            model_name='videos',
            name='iframe',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
