# Generated by Django 2.2.4 on 2020-12-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0018_auto_20201128_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Arquivo - mp4'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='descricao',
            field=models.CharField(max_length=400, verbose_name='Frase'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='ddd',
            field=models.CharField(help_text='DDD do telefone', max_length=4, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='imagem_fundadora',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Foto da Fundadora'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Imagem de logo'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_empresa',
            field=models.CharField(max_length=200, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='número da casa'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='phone_cel',
            field=models.CharField(max_length=200, verbose_name='Telefone celular/Whatsapp'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='phone_com',
            field=models.CharField(max_length=200, verbose_name='Telefone comercial'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço - Rua'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='sobre_fundadora',
            field=models.TextField(verbose_name='Texto sobre a Fundadora'),
        ),
        migrations.AlterField(
            model_name='depoimentos',
            name='funcao',
            field=models.CharField(max_length=200, verbose_name='Cargo/Função'),
        ),
        migrations.AlterField(
            model_name='depoimentos',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='depoimentos',
            name='texto',
            field=models.TextField(verbose_name='Depoimento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ministrantes',
            field=models.TextField(blank=True, null=True, verbose_name='Ministrantes'),
        ),
        migrations.AlterField(
            model_name='listservicos',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='iframe',
            field=models.TextField(help_text='Copie e cole aqui o embed do arquivo', verbose_name='iframe'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('contact', models.ForeignKey(on_delete='SET NULL', related_name='messages', to='administracao.Contatos')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
