# Generated by Django 2.2.4 on 2020-12-30 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0019_auto_20201230_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='email',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='iframe',
            field=models.TextField(blank=True, help_text='Copie e cole aqui o embed do arquivo', null=True, verbose_name='iframe'),
        ),
    ]
