# Generated by Django 2.2.4 on 2021-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0020_auto_20201230_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Arquivo - mp4'),
        ),
    ]
