# Generated by Django 2.2.4 on 2021-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0023_certificados'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='video_institucional',
            field=models.TextField(blank=True, help_text='Copie e cole aqui o embed do arquivo', null=True, verbose_name='Vide Institucional'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Imagem/logo da certificação'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
