# Generated by Django 2.2.4 on 2022-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0026_menus_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
